apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: spark-smoke-events
  namespace: data
  labels:
    strimzi.io/cluster: wexler-kafka
spec:
  topicName: spark-smoke-events
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
